name: parallel-jobs
on:
  push:
    paths:
      - '.github/workflows/06-job-ordering.yml'
jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Print current path
        working-directory: ./06-job-ordering
        run: pwd

      - run: echo "Doing work parallel with job2"
  job_2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Doing work parallel with job1"
  job_3:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - run: echo "job1 done, running job3"
  job_4:
    runs-on: ubuntu-latest
    needs: [job_2, job_3]
    steps:
      - run: echo "job2 & job3 done, running job4"
  job_5:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: job_1
    steps:
      - run: echo "job1 completed with status ${{ needs.job_1.result }}, running job5"
