name: outputs
on:
  push:
    paths:
      - '.github/workflows/08-outputs.yml'
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Print current path
        working-directory: ./08-outputs
        run: pwd
 
      - name: Do Work
        run: |
          echo "FAV_NUMBER=3" >> $GITHUB_OUTPUT
          echo "FAV_COLOR=blue" >> $GITHUB_OUTPUT
        id: abc
      
      - name: Read output
        run: |
          echo "${{steps.abc.outputs.FAV_NUMBER}}"
          echo "${{steps.abc.outputs.FAV_COLOR}}"
    outputs:
      fav-animal: dog
      fav-number: ${{steps.abc.outputs.FAV_NUMBER}}
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: |
         echo "${{needs.job1.outputs.fav-animal}}"
         echo "${{needs.job1.outputs.fav-number}}"
